### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Joecoder55** [igorpeixoto/Schedule-Pointe-to-Google-Calendar#1]
I tried running this and get the error:    Invalid argument (line 106, file "Code")

Any suggestions?

**Comment by igorpeixoto** [comment]
Hey mate! Sorry it took me so long to check this out. It completely vanished in my inbox because I was busy with my graduation project.

I just checked, it throws this error when it can't find any message at all from postmaster[at]schedulepointe.com

Or if you are repurposing the code to another task it will throw this error when it can't find any messages based on your query.

If you want to check this out you can change the query in **line 25** to another sender address/subject.

`// Find messages from sender postmaster@schedulepointe.com and return the first 10.`
`var threads = GmailApp.search('from:postmaster@schedulepointe.com subject:scheduled', 0, 10);`

Once again sorry it took me this long.

Hope you may still find it useful.

I'll try to fix it anyway, thanks for your feedback ;)

Regards!
